### ISSUE TITLE
Problems using it with Laravel Twill built on VueJS

### ISSUE THREAD

**Issue by raz-iacob** [blood72/laravel-blade-minify-compiler#2]
Is there a problem when compiling inline VueJS or Vuex store? I tried using it but the Twill admin that I used stops working.

**Comment by blood72** [comment]
This problem was caused by the structure in which the blade file is minfied.

`<?php ~ ?>` or `<script>` tags, etc. are wrapped and processed separately.
And the space between the tag is considered plain text, and the new line is replaced with a space.

For example, `/vendor/area17/twill/views/layouts/dashboard.blade.php`, the area is in plain text.

The actual `@section('initialStore')` is supposed to be injected inside the script tag.
When processed as plain text, it changes as shown in the picture below, resulting in javascript syntax errors.

<img width="1185" alt="image" src="https://user-images.githubusercontent.com/24821306/179148037-de1a9eef-f26d-447e-9513-e54a5130a59d.png">

The structural problems of the compilation process make it difficult to solve at my level.
The temporary method is to publish the vendor file and attach a semicolon to the back area.
<img width="940" alt="image" src="https://user-images.githubusercontent.com/24821306/179148919-3fcc4e40-410f-482f-a14d-a5652b2cf02d.png">

**Comment by raz-iacob** [comment]
thank you for your detailed answer! This is helpful!
